apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: crawler-deployment
  labels: 
    name: "crawler-deployment"
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/approvals: "1" 
spec:
  selector:
    matchLabels:
      app: crawler
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: diogoferreira/crawler
        envFrom:
          - secretRef:
              name: slack-web-hook
        env:
          - name: STATSD_HOST
            value: "grafana.default.svc.cluster.local"
        imagePullPolicy: Always
