version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $docker_id -p $docker_password
          TAG=$CIRCLE_BUILD_NUM
          docker build -t diogoferreira/crawler .
          docker tag diogoferreira/crawler diogoferreira/crawler:$TAG
          docker tag diogoferreira/crawler diogoferreira/crawler:latest
  push:
    branches:
      only:
        - master
    machine: true
    steps:
      - run: |
          docker push diogoferreira/crawler
      
        


